techfest_website/techfest_website/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from forums import views as forum_views
from events import views as event_views
from updates import views as update_views
from sponsors import views as sponsor_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as django_views
from django.conf.urls import handler404 , handler500


urlpatterns = [
    path('admin_ehsy5cbk3e/', admin.site.urls),
    path('' , user_views.index , name='index'),

    #path('' , include('django.contrib.auth.urls')),
    path('password_reset/', django_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', django_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', django_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', django_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('explore/' , user_views.explore , name='explore'),
    path('users/', include('users.urls' , namespace = 'users')),
    path('forums/', include('forums.urls' , namespace = 'forums')),
    path('updates/', include('updates.urls' , namespace = 'updates')),
    path('events/' , include('events.urls' , namespace = 'events')),
    path('sponsors/' , sponsor_views.sponsor , name='sponsors'),
]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404= user_views.error_404
handler500= user_views.error_500

techfest_website/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views , urls

app_name = 'users'

urlpatterns = [
    path('user_register/', views.register, name='user_register'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('user_logout/' , views.user_logout , name = 'user_logout'),
    path('user_cant_login/ujqCmCpa122w/' , views.login_fail , name = 'login_fail'),
    path('profile/' , views.profile , name = 'profile'),
    path('password_change/', views.change_password, name='change_password'),
    ]

techfest_website/users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.
class TeamMember(models.Model):
    name = models.CharField(max_length=300)
    #image = models.ImageField(upload_to="members")
    image = CloudinaryField('image')
    number = models.IntegerField(unique=True)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
   user = models.OneToOneField(User , on_delete=models.CASCADE)
   first_name = models.CharField(max_length=300 , blank=False)
   last_name = models.CharField(max_length=300 , blank=False)
   college = models.CharField(max_length=300 , blank=False)
   department = models.CharField(max_length=300 , blank=False)
   YEAR = (
        ('School', 'School'),
        ('1st', 'B.tech First'),
        ('2nd', 'B.tech Second'),
        ('3rd', 'B.tech Third'),
        ('4th', 'B.tech Forth'),
        ('M-Tech', 'M.tech'),
        ('PhD', 'PhD'),
        ('Others', 'Others'),
            )
   current_year = models.CharField(max_length=10, choices=YEAR , blank=False)

techfest_website/users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfile

class SignUpForm(forms.ModelForm):
    username = forms.CharField(help_text=False)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget = forms.PasswordInput() ,label='Password:')
    confirm_password = forms.CharField(widget=forms.PasswordInput() , label='Confirm Password:')

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError(" Password and Confirm Password does not match!")
        user = User.objects.filter(username=username)
        if user :
            raise forms.ValidationError("This username is already taken!")

    class Meta():
        model = User
        fields = ['username' , 'email' , 'password' , 'confirm_password']

class SignUpProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfile
        fields = [  'first_name' , 'last_name' , 'college' , 'department' , 'current_year' ]

techfest_website/users/views.py
from django.shortcuts import render
from users.forms import SignUpForm , SignUpProfileForm
# imports for login
from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponseRedirect , HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from users.models import TeamMember , UserProfile
# imports for profile
from events.models import Registration
#import for password change
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm



def index(request):
    members = TeamMember.objects.order_by('number')
    return render(request , 'index.html' , { 'members' : members })

def explore(request):
    return render(request , 'explore.html' , {})

def error_500(request):
    return render(request , 'error_404.html')

def error_404(request):
    return render(request , 'error_404.html')

def register(request):
    registered = False
    user_form = SignUpForm(request.POST or None)
    profile_form = SignUpProfileForm(request.POST or None)
    if user_form.is_valid() and profile_form.is_valid():
        user = user_form.save()
        password = user_form.cleaned_data['password']
        user.set_password(password)
        user.save()

        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        registered = True

    return render(request , 'users/register.html' , { 'registered' : registered , 'user_form' : user_form , 'profile_form' : profile_form })

def login_fail(request):
    return render(request , 'users/login_fail.html' , {})

def user_login(request):
    failed = False
    if request.method=='POST' :
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username = username , password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponseRedirect('/users/user_cant_login/ujqCmCpa122w/')
            failed = True
    else:
        return render(request , 'users/login.html' , { 'failed' : failed })

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

@login_required
def profile(request):
    regs = Registration.objects.filter(user = request.user).order_by('time')
    profile = UserProfile.objects.get(user = request.user)
    return render(request , 'users/profile.html' , { 'regs' : regs , 'profile' : profile , })

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect('/users/profile/')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

techfest_website/templates/users/login.html
{% extends 'base.html' %}
{% block title_block %}
<title>Login | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container-fluid">
<br>
<br>

{% if user.is_authenticated %}
<div class="container">
  <div class="alert alert-info text-center" role="alert">You are already logged in!</div>
</div>
{% else %}
<div class="row justify-content-md-center">
<div class="col-md-5">

  <form action="/users/user_login/" method="post">
    <div class="card" style="border-radius:0px;">
  <h5 class="card-header text-center bg-info" style="border-radius:0px;" >
    <a style=" color: white;">Sign In</a>
  </h5>
  <div class="card-body">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username:</label>
      <input class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
    <label for="password">Password:</label>
    <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-info" type="submit" value="Login"> &nbsp;&nbsp; <a href="{% url 'password_reset' %}">Forgot Password?</a>

  </div>
  <div class="card-footer text-muted">
    Don't have an account! <a href="{% url 'users:user_register' %}">Sign Up Here</a>
  </div>
</div>
</form>
<br>

</div>
</div>
{% endif %}
</div>

{% endblock %}

techfest_website/templates/users/login_fail.html
{% extends 'base.html' %}
{% block title_block %}
<title>Login Failed | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
  <div class="container">
    <div class="alert alert-danger" role="alert">The username and password you entered did not match our records. Please double-check and <strong><a href="{% url 'users:user_login' %}">login</a></strong> again.</div>
  </div>
{% endblock %}

techfest_website/templates/users/profile.html
{% extends 'base.html' %}
{% block title_block %}
<title>Profile | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container-fluid">
<div class="row">
{% if user.is_staff %}
  <div class="col-12">
    <div class="card text-center" style="border-radius:0px;">
      <div class="card-body">
        <div class="card-text">You have rights to access the <a href="{% url 'admin:index' %}" class="alert-link" target="_blank">ADMIN</a> page.</div>
      </div>
    </div>
    <br>
  </div>
{% endif %}
  <div class="col-md-3">
    <div class="card"style="border-radius:0px;">
    <div class="card-header text-center bg-info" style="border-radius:0px;color:white;font-size:1.5rem;padding:1rem;">{{ profile.first_name | upper }} {{ profile.last_name | upper }}</div>
      <div class="card-text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><a style="color:#1e8bff;">Username:</a> {{ user }}</li>
          <li class="list-group-item"><a style="color:#1e8bff;">Email:</a> {{ user.email }}</li>
          <li class="list-group-item"><a style="color:#1e8bff;">College:</a> {{ profile.college }}</li>
          <li class="list-group-item"><a style="color:#1e8bff;">Department:</a> {{ profile.department }}</li>
          <li class="list-group-item"><a style="color:#1e8bff;">Current Year:</a> {{ profile.current_year }}</li>
        </ul>
      </div>
    </div>
    <br>

    <div class="card bg-info text-center" style="border-radius:0px;color:white;">
      <div class="card-body">
        <p class="card-text">This is your profile. Here you can view your registered events.</p><hr>
        <p class="card-text">Feeling Insecure? <strong><a href="{% url 'users:change_password' %}" style="color:#d1e1ff">Change Password!</a></strong></p><hr>
        <p class="card-text">To make changes to your profile please contact <strong>cessgndu@gmail.com</strong></p>
      </div>
    </div>
    <br>
  </div>
  <div class="col-md-9">
    <div class="card text-center" style="border-radius:0px;">
      <div class="card-header bg-info" style="border-radius:0px;color:white;">Registered Events / Workshops</div>
      <div class="card-body">
        <ul class="list-group">
          {% for reg in regs %}
          <li class="list-group-item list-group-item-info">You registered for <strong>{{ reg.event }}</strong> on {{ reg.time }}</li>
          {% empty %}
          <li class="list-group-item list-group-item-warning">No Registerations Yet!</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <br>
  </div>

</div>

</div>
{% endblock %}

techfest_website/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
<title>Signup | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container-fluid">

{% if user.is_authenticated %}
  <div class="container">
    <div class="alert alert-info text-center" role="alert">You are already logged in! You need to logout to register for a new account!</div>
  </div>
{% else %}

<div class="row justify-content-md-center">
<div class="col-md-7">
  {% if registered %}
<div class="container">
    <div class="alert alert-success text-center"><strong>Success!</strong> Thank You for Registering. Now you can <strong><a href="{% url 'users:user_login' %}">login</a></strong></div>
</div>
  {% else %}
  <div class="card" style="border-radius:0px;">
    <h5 class="card-header bg-info text-center" style="background-color : #d1ecf1 ;border-radius:0px;" >
      <a style=" color: white;">Sign Up</a>
    </h5>
    <div class="card-body">
        <a style="color : red ;">{{ user_form.non_field_errors }}<a>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
        <div class="form-group">
        {{ user_form.username.errors }}
        {{ user_form.username | as_crispy_field }}
        </div>
        <div class="row form-row">
          <div class="col-md">
            {{ profile_form.first_name.errors }}
            {{ profile_form.first_name | as_crispy_field }}
          </div>
          <div class="col-md">
            {{ profile_form.last_name.errors }}
            {{ profile_form.last_name | as_crispy_field }}
          </div>
        </div>
        <div class="form-group">
        {{ user_form.email.errors }}
        {{ user_form.email | as_crispy_field }}
        </div>
        <div class="form-group">
        {{ profile_form.college.errors }}
        {{ profile_form.college | as_crispy_field }}
        </div>
        <div class="row form-row">
          <div class="col-md">
            {{ profile_form.ddepartment.errors }}
            {{ profile_form.department | as_crispy_field }}
          </div>
          <div class="col-md">
            {{ profile_form.current_year.errors }}
            {{ profile_form.current_year | as_crispy_field }}
          </div>
        </div>
        <div class="row form-row">
          <div class="col-md">
            {{ user_form.password.errors }}
            {{ user_form.password | as_crispy_field }}
          </div>
          <div class="col-md">
            {{ user_form.confirm_password.errors }}
            {{ user_form.confirm_password | as_crispy_field }}
          </div>
        </div>
        <input class="btn btn-info form-control" type="submit" value="Register">

    </form>
  </div>

  <div class="card-footer text-muted">
    Already Registered? <a href="{% url 'users:user_login' %}">Login Here</a>
  </div>

  </div>
  {% endif %}
</div>
</div>


{% endif %}
</div>
<br>
{% endblock %}