techfest_website/events/urls.py
from django.contrib import admin
from django.urls import path
from events import views , urls

app_name = 'events'

urlpatterns = [
    path('', views.events, name='events_all'),
    path('event_detail/<int:id>/' , views.event_detail , name='event_detail'),
    path('event_payment/' , views.payment , name='payment')
    ]

techfest_website/forums/urls.py
from django.contrib import admin
from django.urls import path
from forums import views , urls

app_name = 'forums'

urlpatterns = [
    path('', views.forums, name='forums_all'),
    path('forum_edit/<int:id>/' , views.forum_edit , name='forum_edit'),
    path('forum_delete/<int:id>/' , views.forum_delete , name='forum_delete'),
    path('comment_edit/<int:id>/' , views.comment_edit , name='comment_edit'),
    path('comment_delete/<int:id>/' , views.comment_delete , name='comment_delete'),
    path('forum_detail/<int:id>/' , views.forum_detail , name='forum_detail'),
    path('forum_like/<int:id>/' , views.forum_like , name='forum_like'),
    ]

techfest_website/techfest_website/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from forums import views as forum_views
from events import views as event_views
from updates import views as update_views
from sponsors import views as sponsor_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as django_views
from django.conf.urls import handler404 , handler500


urlpatterns = [
    path('admin_ehsy5cbk3e/', admin.site.urls),
    path('' , user_views.index , name='index'),

    #path('' , include('django.contrib.auth.urls')),
    path('password_reset/', django_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', django_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', django_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', django_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('explore/' , user_views.explore , name='explore'),
    path('users/', include('users.urls' , namespace = 'users')),
    path('forums/', include('forums.urls' , namespace = 'forums')),
    path('updates/', include('updates.urls' , namespace = 'updates')),
    path('events/' , include('events.urls' , namespace = 'events')),
    path('sponsors/' , sponsor_views.sponsor , name='sponsors'),
]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404= user_views.error_404
handler500= user_views.error_500

techfest_website/updates/urls.py
from django.contrib import admin
from django.urls import path
from updates import views , urls

app_name = 'updates'

urlpatterns = [
    path('', views.updates, name='updates_all'),
    path('update_detail/<int:id>/' , views.update_detail , name='update_detail'),
    ]

techfest_website/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views , urls

app_name = 'users'

urlpatterns = [
    path('user_register/', views.register, name='user_register'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('user_logout/' , views.user_logout , name = 'user_logout'),
    path('user_cant_login/ujqCmCpa122w/' , views.login_fail , name = 'login_fail'),
    path('profile/' , views.profile , name = 'profile'),
    path('password_change/', views.change_password, name='change_password'),
    ]

techfest_website/sponsors/models.py
from django.db import models
from cloudinary.models import CloudinaryField
# Create your models here.
class Sponsor(models.Model):
    name = models.CharField(max_length=300)
    url = models.URLField(max_length=1000 , blank=True)
    image = CloudinaryField('image')
    number = models.IntegerField(unique=True)

    def __str__(self):
        return self.name

techfest_website/sponsors/views.py
from django.shortcuts import render
from sponsors.models import Sponsor
# Create your views here.

def sponsor(request):
    sponsors = Sponsor.objects.order_by('number')
    return render(request , 'sponsors.html' , { 'sponsors' : sponsors })

techfest_website/templates/base.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Guru Nanak Dev University, Amritsar presents you with techno cultural fest of the season POLARIS 2k18 
(26th to 28th OCTOBER, 2018). 
Visit the holy city of Amritsar and taste the culture of Punjab with us. So get ready to dive in a full 3 day venture of technology and amusement and experience the splash of joy!">
    <meta name="theme-color" content = "#050505">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <link rel="icon" sizes="192x192" href="{% static 'icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% block style_block %}
    {% endblock %}
    {% block title_block %}
    <title></title>
    {% endblock %}
    <style media="screen">
      body{
        background-image: url("{% static 'circuit.jpg' %}");
      }
      @media screen and (max-width: 670px){
      .exp-but{
          background-color: #138496 !important;
          border-color: #138496 !important;
          width: 17rem !important;
        }
      .zoom:hover { transform: scale(1) !important; }

      .zoom-spon:hover{
        transform: scale(1) !important;
      }

      .zoom-tile:hover {
        transform: scale(1) !important;
      }
      .zoom-tile:active {
        transform: scale(1) !important;
      }
      }
      .navbar{
        text-align: center;
        padding: 0.67rem;
        background-color: rgba(255, 255, 255, 0);
        border-bottom: 2px solid #032b2b;
        z-index: 4;
      }
      .nav-but{
        font-size: 1.13rem;
        width: 100%;
        background-color: rgba(0, 0, 0, 0.60);
        border-color: #032b2b;
      }
      .nav-but-but{
        background-color: rgba(0, 0, 0, 0.60);
        border-color: #032b2b;
      }
      .nav-but-gp{
        width: 100%;
      }
      .zoom {
        transition: all .2s ease-in-out;
      }
      .zoom:hover {
        transform: scale(1.1);
      }
      .zoom-tile {
        transition: all .2s ease-in-out;
        -webkit-user-select: none; /* Safari */
        -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* IE10+/Edge */
        user-select: none; /* Standard */
      }
      .zoom-tile:hover {
        transform: scale(1.05);
        background-image: url("{% static 'hover.jpg' %}");
        background-size: 25rem;
      }
      .zoom-tile:active {
        transform: scale(1);
      }
      .zoom-spon{
        transition: all .35s ease-in-out;
      }
      .zoom-spon:hover{
        transform: scale(1.05);
      }
      ::-moz-selection { /* Code for Firefox */
    color: white;
    background: #17a2b8;
      }

      ::selection {
    color: white;
    background: #17a2b8;
      }
    </style>
  </head>
<body>
  {% block ring_block %}
  {% endblock %}
  <nav class="navbar navbar-expand-lg navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <div class="container-fluid">
        <div class="row text-center">
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'index' %}" role="button">Home</a></div>
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'events:events_all' %}" role="button">Events/Workshops</a></div>
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'sponsors' %}" role="button">Sponsors</a></div>
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'updates:updates_all' %}" role="button">Updates</a></div>
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'forums:forums_all' %}" role="button">Forums</a></div>
        {% if user.is_authenticated %}
        <div class="col-lg-2">
            <div class="dropdown">
              <button class="btn btn-info nav-but" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </button>
              <div class="dropdown-menu dropdown-menu-right" style="padding:0px;" aria-labelledby="dropdownMenuButton">
                <div class="card-body" style="width:18rem;">
                  {% if user.is_staff %}
                    <div class="alert alert-info" role="alert">{{ user }} <img src="{% static 'verified.png' %}" style="height:1.2rem;"></div>
                    <div class="alert alert-info" role="alert">{{ user.email }}</div>
                  {% else %}
                    <div class="alert alert-info" role="alert">{{ user }}</div>
                    <div class="alert alert-info" role="alert">{{ user.email }}</div>
                  {% endif %}
                  <div class="dropdown-divider"></div>
                  <div class="row form-row">
                    <div class="col">
                      <a class="btn btn-info form-control" href="{% url 'users:profile' %}" role="button">Profile</a>
                    </div>
                    <div class="col">
                      <a class="btn btn-info form-control" href="{% url 'users:user_logout' %}" role="button">Logout</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        {% else %}
        <div class="col-lg-2"><a class="btn btn-info nav-but" href="{% url 'users:user_login' %}" role="button">Login/Signup</a></div>
        {% endif %}
        </div>
      </div>
    </div>
</nav>
<br>
{% block body_block %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
<script  src="{% static 'index.js' %}"></script>
</body>
</html>

techfest_website/templates/error_404.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content = "#050505">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <link rel="icon" sizes="192x192" href="{% static 'icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!--
    <link rel="stylesheet" href="style.css">
  -->
    <title>Error 404 | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
    <style media="screen">
      body{
        /*background-color: #35363d; */
        background-image: url("{% static 'circuit.jpg' %}");
      }
      ::-moz-selection { /* Code for Firefox */
    color: white;
    background: #17a2b8;
      }

      ::selection {
    color: white;
    background: #17a2b8;
      }
    </style>
  </head>
<body>

<div class="container">
  <br>
  <br>
  <br>
  <div class="row justify-content-center">
    <div class="col-sm-6 text-center">
      <img src="{% static 'icon.png' %}" style="height:5rem;">
      <br><br>
      <p style="color: #969696;font: 600 45px/1.5em brandon-grotesque,sans-serif;">PAGE NOT FOUND</p>
      <br>
      <p style="color: white;font-size: 1.9rem;">The link you clicked may be broken or the page may have been removed.</p>
      <br>
      <p style="color:#969696;">VISIT THE <a href='{% url 'index' %}' style="color:#ff3881">HOMEPAGE</a> OR EMAIL US AT <a style="color:#ff3881">cessgndu@gmail.com</a> ABOUT THE PROBLEM<p>
    </div>
  </div>
</div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

techfest_website/templates/explore.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
<title>Explore More | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container">
  <p style="color:white;font-size:2rem;">What's Happening!!</p>
  <br>
  <p style="color:white;font-size:1.5rem;">Entertainment</p>
  <div class="row">
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#17a2b8;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Dance</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#ee1111;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Dramatics</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#17a2b8;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Film & Design</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#603cba;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Arts & Crafts</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color: #ff0097;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Music</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#9f00a7;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Comedy</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#2b5797;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Fashion</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#1e7145;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Culture</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#2b5797;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">History</p>
    </div>
  </div>
  <br>
  <p style="color:white;font-size:1.5rem;">Literature</p>
  <div class="row">
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#2b5797;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Literary</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#9f00a7;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Quizzing</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#17a2b8;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Group Discussion</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#b91d47;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Poetry</p>
    </div>
  </div>
  <br>
  <p style="color:white;font-size:1.5rem;">Interests</p>
  <div class="row">
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#ff0097;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Singing</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#17a2b8;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Sports</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#ee1111;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Camera</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#00aba9;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Painting</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#9f00a7;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Gaming</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#00aba9;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Computing</p>
    </div>
    <div class="col-lg-2 col-md-3 col-5 text-center zoom-tile" style="background-color:#603cba;color:white;height:11rem;margin:5px;display:table;">
      <p style="font-size:1.4rem;display:table-cell;vertical-align:middle;">Science</p>
    </div>
  </div>
  <br>
</div>
{% endblock %}

techfest_website/templates/index.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}
{% block style_block %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<style media="screen">
@media screen and (max-width: 670px){
  #logo{
    height:16rem !important;
  }
  .top-break{
    height: 5px !important;
  }
}
.break{
  position: relative;
  height: 14.8vh;
  z-index: 2;
}
#logo{
  padding: 0px;
  height:20rem;
}
</style>
{% endblock %}
{% block title_block %}
<title>Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}

{% block ring_block %}
<img id="a1" src="{% static 'circle/01.png' %}">
<img id="b1" src="{% static 'circle/02.png' %}">
<img id="a2" src="{% static 'circle/03.png' %}">
<img id="b2" src="{% static 'circle/04.png' %}">
<img id="a3" src="{% static 'circle/05.png' %}">
<img id="b3" src="{% static 'circle/06.png' %}">
<img id="b4" src="{% static 'circle/07.png' %}">
{% endblock %}

{% block body_block %}

<div class="container-fluid"><div class="row"><div class="col-md-12 break top-break"></div></div></div>

<div class="container">
<div class="row justify-content-center">
<div class="col-md-9">
  <div class="row justify-content-center" >
    <div class="col-sm-4 col-10" id="logo">
      <img class="img-fluid" src="{% static 'logo/01.png' %}" id="aa" >
      <img class="img-fluid" src="{% static 'logo/02.png' %}" id="bb" >
      <img class="img-fluid" src="{% static 'logo/03.png' %}" id="cc" >
    </div>
    <div class="col-sm-8 col-10" id="location" style=" padding: 0px; z-index:2;">
      <img class="img-fluid" src="{% static 'logo/text.png' %}">
    </div>
  </div>
</div>
</div>
 <div class="row justify-content-center">
    <div class="col-md-3 text-center" style="padding:1.51vh; z-index:6;">
      {% if user.is_authenticated %}
      <a class="btn btn-info nav-but exp-but" href="{% url 'events:events_all' %}" role="button" style="padding:1.51vh;">REGISTER FOR EVENTS</a>
      {% else %}
      <a class="btn btn-info nav-but exp-but" href="{% url 'users:user_register' %}" role="button" style="padding:1.51vh;">CREATE ACCOUNT</a>
      {% endif %}
    </div>
  </div>
</div>
<div class="container-fluid"><div class="row"><div class="col-md-12 break"></div></div></div>
<div class="container">
  <div class="card text-center foo-1" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;">
    <h5 class="card-header" style="color :#d5d6ff;">About Polaris'18</h5>
    <div class="card-body">
      <p class="card-text" style="color :#d5d6ff;">
        We the students of GNDU Amritsar, are organizing our technical festival POLARIS on (26-October-2018). We are organizing a variety of events that include competitions, exhibitions, lectures as well as workshops. The fest will provide a platform for students from all over the country to showcase their technical skills, compete with each other and most importantly learn from each other and from the lectures and workshops that will be held on various topics. All you need is a learning attitude and you are ready to go!
      </p>
    </div>
  </div>
<br>
  <div class="card text-center foo-1" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;">
    <h5 class="card-header" style="color :#d5d6ff;">About CESS</h5>
    <div class="card-body">
      <p class="card-text" style="color :#d5d6ff;">
        The engine which drives the CET department towards excellence under the guidance of Head of Department Dr. Sandeep Sharma. The aim is to modify the students to extraordinary individuals, increasing their technical skills, experience along with imbibing in them the practical skills and aspects such as integrity, team spirit, cooperation which will help to merge and contribute much easily in the corporate world, above all broadening their perspective. CESS has different teams focusing primarily on the skills such as coding, public speaking, drawing and design, marketing and promotions, thus developing in students the skills imperative in the real world. Several events are organised by CESS throughout the year such as workshops, seminars, techfest enhance technical knowledge and skills, giving the students necessary knowledge and guidance for future endeavours.
      </p>
    </div>
  </div>
<br>
<br>
<br>
<div class="card text-center foo-1" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;">
  <h5 class="card-header" style="color :#d5d6ff;">Our Team</h5>
  <div class="card-body">
    <p class="card-text" style="color :#d5d6ff;">
      A strong team can take a vision and turn it into reality.
    </p>
  </div>
</div>
<br>
<div class="row">
{% for member in members %}
<div class="col-md-3 col-sm-4 col-6">
  <div class="card text-center foo-1" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;" >
    <img class="card-img-top img-fluid" src='{{ member.image.url }}' alt="Card image cap">
    <div class="card-footer" style="color :#d5d6ff; padding: 0.7553vh;">
    {{ member.name }}
  </div>
  </div>
  <br>
</div>
{% endfor %}
</div>
<br>
<br>
<div class="card foo-1" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b">
    <h5 class="card-header text-center" style="color :#d5d6ff;">Contact Us</h5>
  <div class="card-body">
    <p class="card-text" style="color :#d5d6ff;">
      <div class="row">

        <div class="col-md-8" style="color :#d5d6ff;">
          <div class="alert alert-dark" role="alert">
            <div class="row col-md-12">
              Email : &nbsp;<strong>cessgndu@gmail.com</strong>
            </div>
            <div class="row">
              <div class="col-md-6">
                Puneet Saini:<br>+91-98880-96255<br>Ravgeet Dhillon:<br>+91-97802-21904
              </div>
              <div class="col-md-6">
                Rishab Chawla:<br>+91-89686-22195<br>Mohit Sharma:<br>+91-88724-60311
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="row" style="padding:0.7553vh;">
            <a class="btn btn-info form-control" href="https://www.facebook.com/gnducess/" target="_blank" style="color: white; background-color:#3b5998; border-color: #3b5998;">facebook</a>
          </div>
          <div class="row" style="padding:0.7553vh;">
            <a class="btn btn-danger form-control" href="https://www.instagram.com/cess.gndu/?hl=en" target="_blank" style="color:white; background-color:#fb3958; border-color: #fb3958;">instagram</a>
          </div>
          <div class="row" style="padding:0.7553vh;">
            <a class="btn btn-success form-control" href="https://goo.gl/maps/3LyNgTNraw42" target="_blank" style="color: white;background-color: #28a745;border-color: #28a745;" >Google Maps</a>
          </div>
        </div>
      </div>
    </p>
  </div>
</div>
<br>
</div>


{% endblock %}

techfest_website/templates/sponsors.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
<title>Sponsors | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}

<div class="container">
  <p style="color:white;font-size:2rem;">Sponsors</p>
  <br>
<div class="row align-items-center">
  {% for spr in sponsors %}
      <div class="col-md-3 col-sm-4 col-6" >
        <div class="card zoom-spon">
          <a href="{{ spr.url }}" target="_blank"><img class="card-img-top img-thumbnail" src="{{ spr.image.url }}" alt=""></a>
        </div><br>
      </div>
  {% empty %}
  <div class="alert alert-light">
    Lots of Sponsors are coming!
  </div>
  {% endfor %}
</div>

<br>

<div class="alert alert-dark text-center" role="alert">
  <a href="https://drive.google.com/file/d/0B0D6BfkiIVNhQ0psUkdkOXljVVg2QnpncWk2WFQ1d3RRbFZv/view?usp=sharing" target="_blank" style="color:#1b1e21;">View Sponsorship Brochure</a>
</div>

</div>


{% endblock %}