techfest_website/events/urls.py
from django.contrib import admin
from django.urls import path
from events import views , urls

app_name = 'events'

urlpatterns = [
    path('', views.events, name='events_all'),
    path('event_detail/<int:id>/' , views.event_detail , name='event_detail'),
    path('event_payment/' , views.payment , name='payment')
    ]

techfest_website/techfest_website/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from forums import views as forum_views
from events import views as event_views
from updates import views as update_views
from sponsors import views as sponsor_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as django_views
from django.conf.urls import handler404 , handler500


urlpatterns = [
    path('admin_ehsy5cbk3e/', admin.site.urls),
    path('' , user_views.index , name='index'),

    #path('' , include('django.contrib.auth.urls')),
    path('password_reset/', django_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', django_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', django_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', django_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('explore/' , user_views.explore , name='explore'),
    path('users/', include('users.urls' , namespace = 'users')),
    path('forums/', include('forums.urls' , namespace = 'forums')),
    path('updates/', include('updates.urls' , namespace = 'updates')),
    path('events/' , include('events.urls' , namespace = 'events')),
    path('sponsors/' , sponsor_views.sponsor , name='sponsors'),
]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404= user_views.error_404
handler500= user_views.error_500

techfest_website/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views , urls

app_name = 'users'

urlpatterns = [
    path('user_register/', views.register, name='user_register'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('user_logout/' , views.user_logout , name = 'user_logout'),
    path('user_cant_login/ujqCmCpa122w/' , views.login_fail , name = 'login_fail'),
    path('profile/' , views.profile , name = 'profile'),
    path('password_change/', views.change_password, name='change_password'),
    ]

techfest_website/events/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.
class Type(models.Model):
    type = models.CharField(max_length=300)

    def __str__(self):
        return self.type


class Event(models.Model):
    name = models.CharField(max_length=300)
    type = models.ForeignKey(Type , on_delete=models.CASCADE)
    image = CloudinaryField('image')
    description = models.TextField()
    fee = models.IntegerField(default=0)
    eligibility = models.CharField(max_length=300 , default="Everyone")
    venue = models.CharField(max_length=2000)
    start = models.DateTimeField(auto_now=False, auto_now_add=False)
    end = models.DateTimeField(auto_now=False, auto_now_add=False)
    registeration_open = models.BooleanField(default=False)
    #google_form_url = models.URLField(max_length=200 , null=True , blank=True , default='www.example.com')

    def __str__(self):
        return self.name

class Registration(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , default=1 ,on_delete=models.CASCADE)
    event = models.ForeignKey(Event , on_delete=models.CASCADE)
    fee_status = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True,auto_now=False)

    class Meta():
        unique_together = ('event', 'user')

techfest_website/events/forms.py
from django import forms
from events.models import Registration

class RegForm(forms.ModelForm):
#    class Meta():
#        model = Reg
#        fields = []
    class Meta:
        model = Registration
        fields = []

techfest_website/events/views.py
from events.models import Event , Registration
from django.shortcuts import render , get_object_or_404
from events.forms import RegForm
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
def events(request):
    events = Event.objects.order_by('start')
    return render(request , 'events/events.html' , { 'events' : events })

def event_detail(request , id ):
    event = get_object_or_404(Event , id = id )
    if not request.user.is_authenticated:
        regs = Registration.objects.order_by('user')
    else:
        regs = Registration.objects.filter(event=event , user=request.user).order_by('user')

    reg_form = RegForm()
    if request.method == 'POST':
        reg_form = RegForm(request.POST)
        if reg_form.is_valid():
            form = reg_form.save(commit=False)
            form.user = request.user
            form.event = event
            form.save()
            return HttpResponseRedirect(request.path)
    return render(request , 'events/event_detail.html' , { 'event' : event , 'form' : reg_form , 'regs' : regs ,  })

def payment(request):
    return render(request, 'events/payment.html')

techfest_website/templates/events/event_detail.html
{% extends 'base.html' %}
{% block title_block %}
<title>{{ event.type }}: {{ event.name }} | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
<!-- FACEBOOK SHARE BUTTON ONLY WORKS ON HEROKU DEPLOYED VERSION -->
<meta property="og:url"           content="https://polaris.cessgndu.com/{{ request.path }}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="{{ event.type }}: {{ event.name }} | Polaris'18 GNDU, Amritsar" />
<meta property="og:description"   content="This event is for: {{ event.eligibility }}, From: {{ event.start }}, To: {{ event.end }}, Venue: {{ event.venue }}" />
<meta property="og:image"         content="{{ event.image.url }}" />

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}
{% block body_block %}
<!-- FACEBOOK SHARE BUTTON ONLY WORKS ON HEROKU DEPLOYED VERSION -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
<div class="row">
<div class="col-md-4">
  <div class="card text-center" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;" >
    <h5 class="card-header" style="color :#d5d6ff;">{{ event.name }}</h5>
    <img class="card-img-top" src='{{ event.image.url }}' alt="Card image cap">
    <div class="card-body" style="padding : 0px;">
      <!-- FACEBOOK SHARE BUTTON ONLY WORKS ON HEROKU DEPLOYED VERSION -->
      <div class="card-footer" style="padding:5px;color :#d5d6ff;">{{ event.type }} | <div class="fb-share-button" style="" data-href="https://polaris.cessgndu.com/{{ request.path }}" data-layout="button" data-size="small" data-mobile-iframe="false"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div></div>
    </div>
  </div>
  <br>
{% if event.registeration_open %}
<div class="card">
  <div class="card-body">
          <!-- Button trigger modal -->
        {% if user.is_authenticated %}
          {% for reg in regs %}
              {% if event.fee == 0 or reg.fee_status %}
              <ul class="list-group">
                <li class="list-group-item list-group-item-success text-center"><i class="far fa-check-circle"></i> Registered Successfully!</li>
                <li class="list-group-item list-group-item-success text-center"><i class="far fa-check-circle"></i> Fee Payment of ₹{{ event.fee }} Successful!</li>
              </ul>
              {% else %}
              <div class="alert alert-success text-center" role="alert"><i class="far fa-check-circle"></i> Registered Successfully!</div>
              <ul class="list-group">
                <li class="list-group-item list-group-item-info"><i class="fas fa-exclamation-circle"></i> Fee will be collected at event spot!</li>
                <li class="list-group-item list-group-item-info">Or you can pay fee using <a href="{% url 'events:payment' %}"><strong>Paytm</strong></a></li>
              </ul>
              {% endif %}
          {% empty %}
              <div class="alert alert-success text-center" role="alert">Registration is open!</div>
              <button type="button" class="btn btn-info form-control" data-toggle="modal" data-target="#exampleModal">Register</button>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to register for {{ event.name }}?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form method="post">
                      {% csrf_token %}
                      {{ form }}
                      <input type="submit" class="btn btn-primary" value="Register"></input>
                    </form>
                  </div>
                </div>
                </div>
                </div>
            {% endfor %}
        {% else %}
        <!-- Button modal ends -->
        <div class="alert alert-success text-center" role="alert">Registration is open!</div>
        <div class="alert alert-info text-center" role="alert" style="margin-bottom:0px;">You need to <strong><a href="{% url 'users:user_login' %}">login</a></strong> to register</div>
        {% endif %}
    </div>
  </div>
{% else %}
<div class="card">
<div class="card-body">
  <div class="alert alert-danger text-center" role="alert">Registration is not yet open!</div>
  <button type="button" class="btn btn-info form-control" disabled>Register</button>
</div>
</div>
{% endif %}
<br>
</div>

<div class="col-md-8">
  <div class="card" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;" >
    <h5 class="card-header text-center" style="color :#d5d6ff;">About this {{ event.type }}</h5>
    <div class="card-body" style=" color : #d5d6ff">
      {{ event.description | safe }}
    </div>
  </div>
  <br>
  <div class="card">
  <div class="card-header bg-info" style="color:white;">Fee: ₹{{ event.fee }}</div>
  <ul class="list-group">
    <li class="list-group-item">This event is for: {{ event.eligibility }}</li>
    <li class="list-group-item">From: {{ event.start }}</li>
    <li class="list-group-item">To: {{ event.end }}</li>
    <li class="list-group-item">Venue: {{ event.venue }}</li>
  </ul>
</div>
<br>
</div>
</div>
</div>
{% endblock %}

techfest_website/templates/events/events.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
<title>Events/Workshops | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container">
<div class="row">
{% for event in events %}
<div class="col-lg-3 col-md-4 col-sm-6 col-12">
  <div class="card text-center zoom" style="background-color: rgba(63, 63, 63, 0.42) ; border: 2px solid #032b2b ;" >
    <div class="card-header" style="color :#d5d6ff; padding: 4px;">{{ event.type }}</div>
    <img class="card-img-top img-fluid" src='{{ event.image.url }}' alt="Card image cap">
    <div class="card-body" style="padding : 10px;">
      <h5 class="card-title" style="color :#d5d6ff; ">{{ event.name }}</h5>
      <a href="{% url 'events:event_detail' event.id %}" class="btn btn-dark form-control" style="padding : 3px; ">Explore</a>
    </div>
  </div>
  <br>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

techfest_website/templates/events/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
<title>Payment | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}

{% block body_block %}
<div class="container">
<div class="row">
<div class="col-sm-4">
  <div class="card">
    <div class="card-body">
      <img class="card-img-top" src="{% static 'paytm.png' %}" alt="Card image cap">
      <p class="card-text text-center">Scan code in Paytm App</p>
      <img class="card-img-top" src="{% static 'demoqrcode.png' %}" alt="Card image cap">
    </div>
    <div class="card-footer" style="background-color:#01B9F5;padding:0.4rem;"></div>
    <div class="card-footer" style="background-color:#012B74;padding:0.4rem;"></div>
  </div>
  <br>
</div>
<div class="col-sm-8">
  <div class="card">
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item list-group-item-info">1) Open Paytm App</li>
        <li class="list-group-item list-group-item-info">2) Scan this QR Code</li>
        <li class="list-group-item list-group-item-info">3) Enter payment amount</li>
      </ul>
      <br>
      <ul class="list-group">
        <li class="list-group-item list-group-item-info">
          <p>Please provide these details in the message:</p>
          <ul style="list-style-type: circle;">
            <li><strong>Event/Workshop Name</strong></li>
            <li>Your <strong>Username</strong></li>
            <li>Your <strong>Email Address</strong></li>
            <li>Your <strong>Phone No.</strong></li>
          </ul>
        </li>
      </ul>
      <br>
      <ul class="list-group">
        <li class="list-group-item list-group-item-info">After confirming your payment, we will change your fee status to <strong>"PAID SUCCESSFULLY"</strong></li>
        <li class="list-group-item list-group-item-info">In case of any problem, feel free to email us at <strong>cessgndu@gmail.com</strong></li>
      </ul>
    </div>
  </div>
  <br>
</div>
</div>
</div>
{% endblock %}