techfest_website/forums/urls.py
from django.contrib import admin
from django.urls import path
from forums import views , urls

app_name = 'forums'

urlpatterns = [
    path('', views.forums, name='forums_all'),
    path('forum_edit/<int:id>/' , views.forum_edit , name='forum_edit'),
    path('forum_delete/<int:id>/' , views.forum_delete , name='forum_delete'),
    path('comment_edit/<int:id>/' , views.comment_edit , name='comment_edit'),
    path('comment_delete/<int:id>/' , views.comment_delete , name='comment_delete'),
    path('forum_detail/<int:id>/' , views.forum_detail , name='forum_detail'),
    path('forum_like/<int:id>/' , views.forum_like , name='forum_like'),
    ]

techfest_website/techfest_website/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from forums import views as forum_views
from events import views as event_views
from updates import views as update_views
from sponsors import views as sponsor_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as django_views
from django.conf.urls import handler404 , handler500


urlpatterns = [
    path('admin_ehsy5cbk3e/', admin.site.urls),
    path('' , user_views.index , name='index'),

    #path('' , include('django.contrib.auth.urls')),
    path('password_reset/', django_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', django_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', django_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', django_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('explore/' , user_views.explore , name='explore'),
    path('users/', include('users.urls' , namespace = 'users')),
    path('forums/', include('forums.urls' , namespace = 'forums')),
    path('updates/', include('updates.urls' , namespace = 'updates')),
    path('events/' , include('events.urls' , namespace = 'events')),
    path('sponsors/' , sponsor_views.sponsor , name='sponsors'),
]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404= user_views.error_404
handler500= user_views.error_500

techfest_website/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views , urls

app_name = 'users'

urlpatterns = [
    path('user_register/', views.register, name='user_register'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('user_logout/' , views.user_logout , name = 'user_logout'),
    path('user_cant_login/ujqCmCpa122w/' , views.login_fail , name = 'login_fail'),
    path('profile/' , views.profile , name = 'profile'),
    path('password_change/', views.change_password, name='change_password'),
    ]

techfest_website/forums/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , default=1 ,on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True,auto_now=False)
    text = models.CharField(max_length=1000 )

    def __str__(self):
        return self.text

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , default=1 ,on_delete=models.CASCADE)

    to_question = models.ForeignKey(Question , on_delete=models.CASCADE)
    #content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    #object_id = models.PositiveIntegerField()
    #content_object = GenericForeignKey('content_type', 'object_id')

    time = models.DateTimeField(auto_now_add=True,auto_now=False)
    text = models.TextField()

    def __str__(self):
        return self.text

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , default=1 ,on_delete=models.CASCADE)
    to_comment = models.ForeignKey(Comment , on_delete=models.CASCADE)

    class Meta():
        unique_together = ('to_comment', 'user')

techfest_website/forums/forms.py
from django import forms
from forums.models import Question , Comment , Like


class QuestionForm(forms.ModelForm):
    text = forms.CharField(label='Your Question:' , widget=forms.Textarea(attrs={'rows':4,}))
    class Meta():
        model = Question
        fields = ['text']


class CommentForm(forms.ModelForm):
    text = forms.CharField(label='Your Answer:' , widget=forms.Textarea(attrs={'rows':4,}))
    class Meta():
        model = Comment
        fields = ['text']

class LikeForm(forms.ModelForm):
    class Meta():
        model = Like
        fields = []

techfest_website/forums/views.py
from django.shortcuts import render , get_object_or_404
from forums.models import Question , Comment , Like
from forums.forms import QuestionForm , CommentForm , LikeForm
from django.http import HttpResponseRedirect
# Create your views here.

def forums(request):
    questions = Question.objects.order_by('-time')

    questionform = QuestionForm(request.POST or None)
    if questionform.is_valid():
        qform = questionform.save(commit=False)
        qform.user = request.user
        qform.save()
        return HttpResponseRedirect("/forums/")
    return render(request , 'forums/forums.html' , { 'questions' : questions , 'questionform' : questionform ,  })

def forum_edit(request , id):
    question = get_object_or_404(Question , id = id )
    editform = QuestionForm(request.POST or None , instance=question)
    if editform.is_valid():
        eform = editform.save(commit=False)
        eform.save()
        return HttpResponseRedirect("/forums/")
    return render(request , 'forums/forum_edit.html' , { 'question' : question , 'editform' : editform })

def forum_delete(request , id):
    question = get_object_or_404(Question , id = id )
    if request.method=='POST':
        question.delete()
        return HttpResponseRedirect("/forums/")
    return render(request , 'forums/forum_delete.html' , { 'question' : question })

def forum_detail(request , id ):
    question = get_object_or_404(Question , id = id )
    comments = Comment.objects.filter(to_question = question).order_by('time')
    commentform = CommentForm(request.POST or None)
    if commentform.is_valid():
        cform = commentform.save(commit=False)
        cform.user = request.user
        cform.to_question = question
        cform.save()
        return HttpResponseRedirect( request.path )
    return render(request , 'forums/forum_detail.html' , { 'question' : question , 'comments' : comments , 'commentform' : commentform })

def comment_edit(request , id):
    question = get_object_or_404(Comment , id = id )
    editform = CommentForm(request.POST or None , instance=question)
    if editform.is_valid():
        eform = editform.save(commit=False)
        eform.save()
        return HttpResponseRedirect("/forums/")
    return render(request , 'forums/forum_edit.html' , { 'question' : question , 'editform' : editform })

def comment_delete(request , id):
    question = get_object_or_404(Comment , id = id )
    if request.method=='POST':
        question.delete()
        return HttpResponseRedirect("/forums/")
    return render(request , 'forums/forum_delete.html' , { 'question' : question })

def forum_like(request , id):
    comment = get_object_or_404(Comment , id = id)
    likes = Like.objects.filter(to_comment = comment)
    likeform = LikeForm(request.POST or None)

    if not request.user.is_authenticated:
        like_check = Like.objects.order_by('user')
    else:
        like_check = Like.objects.filter(to_comment = comment , user=request.user).order_by('user')

    if likeform.is_valid():
        lform = likeform.save(commit=False)
        lform.user = request.user
        lform.to_comment = comment
        lform.save()
        return HttpResponseRedirect( request.path )
    return render(request , 'forums/forum_like.html' , { 'comment' : comment , 'likeform' : likeform , 'likes' : likes , 'like_check' : like_check ,})

techfest_website/templates/forums/forum_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %}
<title>Forums | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container">
{% if question.user == user %}
  <div class="card" style="border-radius:0px;">
    <div class="card-header bg-danger" style="border-radius:0px;color:white;">
      By : {{ question.user }} , <a class="date">{{ question.time | timesince }} ago</a>
    </div>
    <div class="card-body">
      <div class="alert alert-danger" role="alert">
        Are you sure you want to delete this record?
      </div>
      <div class="alert alert-danger" role="alert">
        {{ question.text }}
      </div>
      <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" autocomplete="off" value="Delete">
      </form>
    </div>
  </div>
  <br>
  {% else %}
  <div class="alert alert-info text-center">
    Invalid Request!
  </div>
  {% endif %}
</div>
{% endblock %}

techfest_website/templates/forums/forum_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block style_block %}
<style media="screen">
  iframe{
    -webkit-user-select: none; /* Safari */
    -moz-user-select: none; /* Firefox */
    -ms-user-select: none; /* IE10+/Edge */
      user-select: none; /* Standard */
  }
</style>
{% endblock %}
{% block title_block %}
<title>Forum: {{ question.text }} | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container-fluid">
<div class="card" style="border-radius:0px;">
  {% if question.user.is_staff %}
    <div class="card-header">By : {{ question.user }} <img src="{% static 'verified.png' %}" style="height:1.2rem;"> , <a class="date">{{ question.time | timesince }} ago</a></div>
  {% else %}
    <div class="card-header">By : {{ question.user }}  , <a class="date">{{ question.time | timesince }} ago</a></div>
  {% endif %}
  <div class="card-body" style="background-color:#e0e0e0;">
    <h5 class="card" style="border-radius:0px;"><div class="card-body">{{ question.text }}</div></h5>
    <br>
    {% for comment in comments %}
          <div class="card" style="border-radius:0px;">
            <div class="card-header" style="border-radius:0px;">
              {% if comment.user.is_staff %}
              <p class="card-text"><small>By : {{ comment.user }} <img src="{% static 'verified.png' %}" style="height:1rem;"> ,
                {% if comment.user == user %}
                <a class="date">{{ comment.time | timesince }} ago&nbsp;&nbsp;<a class="badge badge-info" style="font-size:0.8rem;" href='{% url 'forums:comment_edit' comment.id %}'>Edit</a>&nbsp;<a class="badge badge-danger" style="font-size:0.8rem;" href='{% url 'forums:comment_delete' comment.id %}'>Delete</a></a>
                {% else %}
                <a class="date">{{ comment.time | timesince }} ago</a>
                {% endif %}
              </small></p>
              {% else %}
              <p class="card-text"><small>By : {{ comment.user }} ,
                {% if comment.user == user %}
                <a class="date">{{ comment.time | timesince }} ago&nbsp;&nbsp;<a class="badge badge-info" style="font-size:0.8rem;" href='{% url 'forums:comment_edit' comment.id %}'>Edit</a>&nbsp;<a class="badge badge-danger" style="font-size:0.8rem;" href='{% url 'forums:comment_delete' comment.id %}'>Delete</a></a>
                {% else %}
                <a class="date">{{ comment.time | timesince }} ago</a>
                {% endif %}
              </small></p>
              {% endif %}
            </div>
                <div class="card-body">
                    <p class="card-text">{{ comment.text | linebreaksbr | urlize }}</p>
                </div>
                <!--
                {% if comment.user.is_staff %}
                  <div class="card-footer text-muted">{{ comment.user }} <img src="{% static 'verified.png' %}" style="height:1.2rem;"> , <a class="date">{{ comment.time | timesince }}</a></div>
                {% else %}
                  <div class="card-footer text-muted">{{ comment.user }} , <a class="date">{{ comment.time | timesince }}</a></div>
                {% endif %}
              -->
              <iframe src='{% url 'forums:forum_like' comment.id %}' style="border-style:none;height:4rem;" scrolling="no"></iframe>
          </div>
          <br>
    {% empty %}
    <div class="alert alert-warning" role="alert">Be the first one to answer!</div>
    {% endfor %}
    </div>
    <div class="card-footer">
    {% if user.is_authenticated %}
        <form method="post">
          {% csrf_token %}
          {{ commentform | crispy }}
          <input class="btn btn-info" type="submit" value="Answer">
        </form>
    {% else %}
    <div class="row">
      <div class="col-md">
        <div class="card text-center" style="color: #004085;background-color: #cce5ff;border-color: #b8daff;">
          <div class="card-body">You need to <strong><a href='{% url 'users:user_login' %}'>login</a></strong> to upvote or answer.</div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  </div>
  <br>
</div>


{% endblock %}

techfest_website/templates/forums/forum_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %}
<title>Forums | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container">
{% if question.user == user %}
  <div class="card" style="border-radius:0px;">
    <div class="card-header bg-info" style="border-radius:0px;color:white;">
      By : {{ question.user }} , <a class="date">{{ question.time | timesince }} ago</a>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ editform | crispy }}
        <input type="submit" class="btn btn-info" autocomplete="off" value="Save">
      </form>
    </div>
  </div>
  <br>
{% else %}
<div class="alert alert-info text-center">
  Invalid Request!
</div>
{% endif %}
</div>
{% endblock %}

techfest_website/templates/forums/forum_like.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <title></title>
    <style media="screen">
      body{
        margin: 0px;
        padding: 0px;
        -webkit-user-select: none; /* Safari */
        -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* IE10+/Edge */
          user-select: none; /* Standard */
      }
      .btn:focus,.btn:active:focus,.btn.active:focus, .btn.focus,.btn:active.focus,.btn.active.focus {
        outline: none !important;
        box-shadow: none !important;
      }
    </style>
  </head>
<body unselectable="on">
  <div class="container-fluid">
    <div class="row align-items-center">
      {% if user.is_authenticated %}
      <div class="col-sm">
        {% for like in like_check %}
        <div class="btn-group" role="group" aria-label="Basic example">
          <a class="btn btn-outline-info form-control text-center" style="color:white;margin-bottom:1rem;padding: .65rem 1.15rem;background-color:#17a2b8;"><img src="{% static 'tick.png' %}" style="height:1.5rem;">&nbsp;Upvote</a>
          <a class="btn btn-outline-info form-control " style="margin-bottom:1rem;color: white;padding: .65rem 1.15rem; background-color:#17a2b8;">{{ likes.count }}</a>
        </div>
        {% empty %}

            <form method="post">
              {% csrf_token %}
              {{ likeform | crispy }}
              <div class="btn-group" role="group" aria-label="Basic example">
                <button class="btn btn-outline-info form-control text-center" style="margin-bottom:1rem;padding: .65rem 1.15rem;" type="submit"><img src="{% static 'arrow.png' %}" style="height:1.5rem;">&nbsp;Upvote</button>
                <a class="btn btn-outline-info form-control " style="margin-bottom:1rem;color: white;padding: .65rem 1.15rem; background-color:#17a2b8;">{{ likes.count }}</a>
              </div>
            </form>
        {% endfor %}
      </div>
      {% else %}
      <div class="col-sm">
      <div class="btn-group" role="group" aria-label="Basic example">
        <a class="btn btn-outline-info form-control text-center disabled" style="color:white;margin-bottom:1rem;padding: .65rem 1.15rem;background-color:#17a2b8;"><img src="{% static 'arrow.png' %}" style="height:1.5rem;">&nbsp;Upvote</a>
        <a class="btn btn-outline-info form-control " style="margin-bottom:1rem;color: white;padding: .65rem 1.15rem; background-color:#17a2b8;">{{ likes.count }}</a>
      </div>
      </div>
      {% endif %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

techfest_website/templates/forums/forums.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %}
<title>Forums | Polaris 2k18 - The TechFest | Guru Nanak Dev University</title>
{% endblock %}
{% block body_block %}
<div class="container-fluid">
<div class="row">
  <div class="col-md-3">

    <div class="card text-center" style="border-radius:0px;">
      <h5 class="card-header">Welcome to Forums</h5>
    <div class="card-body">
      <div class="alert alert-info" style="margin-bottom:0px;">
      Here you can ask questions, share your experiences, and discuss topics of mutual interest.
    </div>
    </div>
    </div>

    <br>
    <div class="card" style="border-radius:0px;">
      <h5 class="card-header">Have doubts? Feel free to ask questions.</h5>
      <div class="card-body">
        {% if user.is_authenticated %}
          <!-- <a href="#" class="btn btn-success form-control">Ask Question</a> -->
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-info form-control" data-toggle="modal" data-target="#exampleModal">Ask a Question</button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Ask a Question</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="post" >
                  <div class="modal-body">
                  {% csrf_token %}
                  {{ questionform | crispy }}
                  </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input type="submit" class="btn btn-info" autocomplete="off" value="Ask">
                </div>
              </form>
              </div>
            </div>
          </div>
        {% else %}
        <div class="alert alert-info" style="margin-bottom:0px;" role="alert">You need to <strong><a href='{% url 'users:user_login' %}'>login</a></strong> to ask questions.</div>
        {% endif %}
      </div>
    </div>
    <br>
  </div>
<div class="col-md-6">
  <div class="card" style="border-radius:0px;">
    <div class="card-header text-center bg-info" style="border-radius:0px;color: white;">Questions asked by users</div>
    <div class="card-body" style="padding:10px;">
      <ul class="list-group list-group-flush">
      {% for question in questions %}
        <li class="list-group-item">
          <h5 class="card-title"><a href="{% url 'forums:forum_detail' question.id %}" style="color: #212529;">{{ question.text }}</a></h5>
            {% if question.user.is_staff %}
            <p class="card-text"><small class="text-muted">By : {{ question.user }} <img src="{% static 'verified.png' %}" style="height:1rem;"> ,
              {% if question.user == user %}
              <a class="date">{{ question.time | timesince }} ago&nbsp;&nbsp;<a class="badge badge-info" style="font-size:0.8rem;" href='{% url 'forums:forum_edit' question.id %}'>Edit</a>&nbsp;<a class="badge badge-danger" style="font-size:0.8rem;" href='{% url 'forums:forum_delete' question.id %}'>Delete</a></a>
              {% else %}
              <a class="date">{{ question.time | timesince }} ago</a>
              {% endif %}
            </small></p>
            {% else %}
            <p class="card-text"><small class="text-muted">By : {{ question.user }} ,
              {% if question.user == user %}
              <a class="date">{{ question.time | timesince }} ago,&nbsp;&nbsp;<a class="badge badge-info" style="font-size:0.8rem;" href='{% url 'forums:forum_edit' question.id %}'>Edit</a>&nbsp;<a class="badge badge-danger" style="font-size:0.8rem;" href='{% url 'forums:forum_delete' question.id %}'>Delete</a></a>
              {% else %}
              <a class="date">{{ question.time | timesince }} ago</a>
              {% endif %}
            </small></p>
            {% endif %}
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>
  <br>
</div>

<div class="col-md-3">
  <div class="card" style="border-radius:0px;">
    <div class="card-header text-center bg-info" style="border-radius:0px;color: white;">Questions picked for you</div>
  <div style="padding:5px;">
  <ul class="list-group list-group-flush">
    {% for question in questions %}
      {% if question.user.is_staff %}
      <li class="list-group-item">
      <p class="card-text"><a href="{% url 'forums:forum_detail' question.id %}">{{ question.text }}</a></p>
    </li>
      {% endif %}
    {% endfor %}
  </ul>
  </div>
  </div>
  <br>
</div>
</div>
</div>
{% endblock %}